SOURCES = {
    1: [
        ('DIRECT', 'partial_direct_T1.cpp'),
        ('ENUM', 'partial_enum_T1.cpp'),
        ('CUBE', 'partial_cube_T1.cpp'),
        ('MID', 'partial_mid_T1.cpp'),
        ('ZERO', 'partial_zero_T1.cpp'),
        ('SINGLETON', 'partial_singleton_T1.cpp'),
        ('COVER', 'partial_cover_T1.cpp'),
        ('DISJOINT', 'partial_disjoint_T1.cpp'),
        ('ONLYFOURTH', 'partial_only_fourth_T1.cpp'),
        ('SUM', 'partial_sum_T1.cpp'),
        ('STD', 'T1.cpp'),
    ],
    2: [
        ('PARTIAL', 'partial_T2.cpp'),
        ('SUBSET', 'partial_subset_T2.cpp'),
        ('MID', 'partial_mid_T2.cpp'),
        ('IMPOSSIBLE', 'partial_impossible_T2.cpp'),
        ('PURE', 'partial_pure_T2.cpp'),
        ('TRIPLES', 'partial_triples_T2.cpp'),
        ('ALTERNATING', 'partial_alternating_T2.cpp'),
        ('STD', 'T2.cpp'),
    ],
    3: [
        ('BRUTE', 'partial_brute_T3.cpp'),
        ('MID', 'partial_T3.cpp'),
        ('CONSECUTIVE', 'partial_consecutive_T3.cpp'),
        ('NEIGHBOR', 'partial_neighbor_T3.cpp'),
        ('STD', 'T3.cpp'),
    ],
    4: [
        ('BRUTE', 'partial_brute_T4.cpp'),
        ('MID', 'partial_T4.cpp'),
        ('UNCHANGED', 'partial_unchanged_T4.cpp'),
        ('INCREASING', 'partial_increasing_T4.cpp'),
        ('FIRST', 'partial_first_T4.cpp'),
        ('PAIR', 'partial_pair_T4.cpp'),
        ('STD', 'T4.cpp'),
    ],
}
